import './swiper'
import '../scss/index.scss'
import './left-float-menu'
import './menu-feedback'
import './menu-call'
import './hiding-buttons'
import './hiding-buttons-brands'
import './hiding-buttons-types-of-equip'
